const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createGateController}=require('../integration/portail-shelly.js');
const Access=require('../dist/access.js');
function clock(){let t=0,id=0;const tasks=new Map();return {now:()=>t,schedule:(ms,fn)=>{tasks.set(++id,{at:t+ms,fn});return id;},cancel:id=>tasks.delete(id),tick(ms){const end=t+ms;while(true){const next=[...tasks].sort((a,b)=>a[1].at-b[1].at)[0];if(!next||next[1].at>end)break;t=next[1].at;tasks.delete(next[0]);next[1].fn();}t=end;}};}
function fixture({failAt,hold=false}={}){const c=clock(),pulses=[],callbacks=[];const engine=createGateController({...c,pulse(active,due,done){if(!active())return done('cancelled',c.now());pulses.push(c.now());if(hold){callbacks.push(done);return;}done(pulses.length===failAt?'no acknowledgement':null,c.now());}});return {c,pulses,engine,callbacks};}
test('Voiture: exactly one pulse; no software closing command later',()=>{const f=fixture();f.engine.start('car-test-1','car',false);f.c.tick(120000);assert.deepEqual(f.pulses,[0]);assert.equal(f.engine.status().state,'done');});
test('Piéton: exactly 0, 5 and 35 seconds, independently of a browser',()=>{const f=fixture();f.engine.start('pedestrian-test','pedestrian',true);f.c.tick(4999);assert.deepEqual(f.pulses,[0]);f.c.tick(1);assert.deepEqual(f.pulses,[0,5000]);assert.equal(f.engine.status().nextIn,30);f.c.tick(30000);assert.deepEqual(f.pulses,[0,5000,35000]);assert.equal(f.engine.status().pulses,3);});
test('Deduplication and shared lock prevent duplicate, overlapping and rapid car/pedestrian commands',()=>{const f=fixture();f.engine.start('same-request','pedestrian',true);f.engine.start('same-request','pedestrian',true);assert.throws(()=>f.engine.start('different-request','car',false));assert.throws(()=>f.engine.start('same-request','car',false));f.c.tick(35000);assert.throws(()=>f.engine.start('new-request','car',false));f.c.tick(10000);f.engine.start('same-request','pedestrian',true);assert.equal(f.pulses.length,3);f.engine.start('new-request','car',false);assert.equal(f.pulses.length,4);});
test('Unconfirmed starting position and failed acknowledgement never schedule closing',()=>{const a=fixture();assert.throws(()=>a.engine.start('unsafe-start','pedestrian',false));assert.equal(a.pulses.length,0);const b=fixture({failAt:2});b.engine.start('failed-stop','pedestrian',true);b.c.tick(60000);assert.deepEqual(b.pulses,[0,5000]);assert.equal(b.engine.status().state,'error');});
test('Cancel removes future impulses without sending a stop or close command',()=>{const f=fixture();f.engine.start('cancel-request','pedestrian',true);f.c.tick(6000);f.engine.cancel('cancel-request');f.c.tick(120000);assert.deepEqual(f.pulses,[0,5000]);assert.equal(f.engine.status().state,'cancelled');});
test('A synchronous transport failure leaves no pending sequence or stuck in-flight lock',()=>{const c=clock(),e=createGateController({...c,pulse(){throw Error('RPC limit');}});e.start('rpc-failure','pedestrian',true);assert.equal(e.status().state,'error');assert.equal(e.status().busy,false);c.tick(60000);assert.equal(e.status().pulses,0);});
test('Cancel during an in-flight request keeps new commands locked and ignores its late acknowledgement',()=>{const f=fixture({hold:true});f.engine.start('pending-request','pedestrian',true);f.engine.cancel('pending-request');f.c.tick(15000);assert.throws(()=>f.engine.start('next-request','car',false));f.callbacks[0](null,0);f.c.tick(60000);assert.deepEqual(f.pulses,[0]);assert.equal(f.engine.status().state,'cancelled');});
test('Settings migration adopts supplied IPs and 0.5-second gate pulse without erasing energy or virtual settings',()=>{const c={relays:[{key:'gate',ip:'',seconds:1,channel:1},{key:'garage',ip:'',seconds:1}],meters:[{ip:'192.168.1.11'}],virtual:{label:'Mon état',component:'text:204'}};const next=Access.migrate(c);assert.equal(next.relays[0].ip,'192.168.1.114');assert.equal(next.relays[1].ip,'192.168.1.10');assert.equal(next.relays[0].seconds,.5);assert.equal(next.relays[0].channel,1);assert.equal(next.virtual.component,'text:204');assert.equal(c.relays[0].seconds,1);assert.equal(next.meters,c.meters);assert.deepEqual(Access.migrate(next),next);});
test('Virtual reads only use documented scalar GetStatus methods and IDs 200–299',()=>{assert.equal(Access.virtualPath('text:204'),'/rpc/Text.GetStatus?id=204');assert.equal(Access.virtualPath('boolean:200'),'/rpc/Boolean.GetStatus?id=200');for(const s of ['button:200','text:1','text:300','switch:0','text:204&method=Switch.Set'])assert.throws(()=>Access.virtualPath(s));});
test('The actual Shelly adapter emits 0.5 s pulses, starts idle and validates credentials',()=>{
  const c=clock(),sent=[],endpoints={};let on=false;
  const context=vm.createContext({print(){},Math,JSON,Error,Timer:{set:(ms,repeat,fn)=>c.schedule(ms,fn),clear:c.cancel},Shelly:{getUptimeMs:c.now,getComponentStatus(name){return name==='wifi'?{sta_ip:'192.168.1.114'}:name==='eth'?{}:{output:on};},call(method,args,cb){assert.equal(method,'Switch.Set');sent.push({at:c.now(),duration:args.toggle_after});const previous=on;on=true;c.schedule(args.toggle_after*1000,()=>on=false);cb({was_on:previous},0);}},HTTPServer:{registerEndpoint(name,fn){endpoints[name]=fn;}}});
  vm.runInContext(fs.readFileSync(require.resolve('../integration/portail-shelly.js'),'utf8'),context);assert.equal(sent.length,0);
  vm.runInContext("PORTAIL.confirmed=true;PORTAIL.transport='local';PORTAIL.token='test-token-12345678901234567890';",context);
  function req(data){let result;const res={send(){result={status:this.code,data:JSON.parse(this.body)};}};endpoints.gate({method:'POST',body:JSON.stringify(data)},res);return result;}
  assert.equal(req({action:'start',id:'denied-request',mode:'car',token:'wrong'}).status,403);assert.equal(sent.length,0);
  const start=req({action:'start',id:'adapter-request',mode:'pedestrian',closed:true,token:'test-token-12345678901234567890'});assert.equal(start.status,200);c.tick(60000);
  assert.deepEqual(sent,[{at:0,duration:.5},{at:5000,duration:.5},{at:35000,duration:.5}]);assert.equal(on,false);
});
